[package]
name = "encryption_api_services_rust_sdk"
version = "0.1.0"
edition = "2021"
description = "SDK to access the encryption API through Rust crate"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
